// <auto-generated />
using ContasBancarias.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContasBancarias.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211111012438_ContasBancarias")]
    partial class ContasBancarias
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ContasBancarias")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContasBancarias.Domain.Models.Bancos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bancos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = false,
                            Codigo = "001",
                            Nome = "BANCO DO BRASIL"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = false,
                            Codigo = "070",
                            Nome = "BRB"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = false,
                            Codigo = "104",
                            Nome = "CAIXA ECONÔMICA FEDERAL"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = false,
                            Codigo = "429",
                            Nome = "BANCO INTER"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = false,
                            Codigo = "237",
                            Nome = "BRADESCO"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = false,
                            Codigo = "008",
                            Nome = "SANTANDER"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = false,
                            Codigo = "756",
                            Nome = "SICOOB"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = false,
                            Codigo = "048",
                            Nome = "ITAU"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = false,
                            Codigo = "422",
                            Nome = "SAFRA"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = false,
                            Codigo = "477",
                            Nome = "CITIBANK"
                        });
                });

            modelBuilder.Entity("ContasBancarias.Domain.Models.Contas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BancoId")
                        .HasColumnType("int");

                    b.Property<string>("CpfOuCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("NomeOuRazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroAgencia")
                        .HasColumnType("int");

                    b.Property<int>("NumeroConta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("ContasBancarias.Domain.Models.Contas", b =>
                {
                    b.HasOne("ContasBancarias.Domain.Models.Bancos", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");
                });
#pragma warning restore 612, 618
        }
    }
}
